# Generated by Django 2.0.4 on 2018-04-07 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cdetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_id', models.CharField(max_length=250)),
                ('date', models.CharField(max_length=250)),
                ('directed_to', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cname', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='cdetails',
            name='c_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='change.Complaint'),
        ),
    ]
