# Generated by Django 2.0.4 on 2018-04-07 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('change', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cdetails',
            name='c_name',
        ),
        migrations.RenameField(
            model_name='complaint',
            old_name='Cname',
            new_name='c_id',
        ),
        migrations.AddField(
            model_name='complaint',
            name='c_name',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='complaint',
            name='date',
            field=models.CharField(default=' ', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='complaint',
            name='directed_to',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Cdetails',
        ),
    ]
